name: Deploy to Firebase Hosting on Merge
on:
  push:
    branches:
      - main  # Ganti jadi master jika branch kamu namanya master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseToken: '${{ secrets.FIREBASE_TOKEN }}'
          channelId: live
          projectId: d-x-gr
